#pragma config(Sensor, dgtl1,  FloorLight1,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  FloorLight2,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  FloorLight3,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  CallFloor1,     sensorTouch)
#pragma config(Sensor, dgtl5,  CallFloor2,     sensorTouch)
#pragma config(Sensor, dgtl6,  CallFloor3,     sensorTouch)
#pragma config(Sensor, dgtl7,  SendFloor1,     sensorTouch)
#pragma config(Sensor, dgtl8,  SendFloor2,     sensorTouch)
#pragma config(Sensor, dgtl9,  SendFloor3,     sensorTouch)
#pragma config(Sensor, dgtl10, ElevatorEncoder, sensorQuadEncoder)
#pragma config(Motor,  port2,  ElevateMotor,  tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



const int MoveSpeed = 30;
const int MoveSpeedDown= 25;
const int PIDSpeedUp = 25;
const int PIDSpeedDown = 15;

const int Error = 5;
const int SlowError = 5;

const int Level1Setpoint = -35;
const int Level2Setpoint = -212;
const int Level3Setpoint = -347;

const int LEDThresholdFloor1 = -131;
const int LEDThresholdFloor2 = -131;
const int LEDThresholdFloor3 = -279.5;

int TargetPose=0;

task main() {
	TargetPose = SensorValue(ElevatorEncoder);

	while (true) {

if (SensorValue[ElevatorEncoder] > (TargetPose-5) && (SensorValue[ElevatorEncoder] < (TargetPose+5)))
				{
		stopMotor(ElevateMotor);
		goto 1;
		}


	if (SensorValue[ElevatorEncoder] < (TargetPose-30)) {
		startMotor(ElevateMotor, MoveSpeedDown);
		}
		if (SensorValue[ElevatorEncoder] > (TargetPose+30)) {
		startMotor(ElevateMotor, -MoveSpeed);
		}

		if (SensorValue[ElevatorEncoder] < (TargetPose+20)) {
		startMotor(ElevateMotor, PIDSpeedDown);
		}
		if (SensorValue[ElevatorEncoder] > (TargetPose-20)) {
		startMotor(ElevateMotor, -PIDSpeedUp);
		}
		label 1;



		if (SensorValue[CallFloor1]==1) {
		TargetPose = -50;
		}
		if (SensorValue[CallFloor2]==1) {
		TargetPose = Level2Setpoint;
		}
		if (SensorValue[CallFloor3]==1) {
		TargetPose = Level3Setpoint;
	}


			if (SensorValue[SendFloor1]==1) {
		TargetPose = Level1Setpoint;
		}
		if (SensorValue[SendFloor2]==1) {
		TargetPose = Level2Setpoint;
		}
		if (SensorValue[SendFloor3]==1) {
		TargetPose = Level3Setpoint;
	}
		if (SensorValue(ElevatorEncoder)<LEDThresholdFloor1){turnLEDOff(FloorLight1);}
		if (SensorValue(ElevatorEncoder)>LEDThresholdFloor1){turnLEDOff(FloorLight2);}
		if (SensorValue(ElevatorEncoder)<LEDThresholdFloor3){turnLEDOff(FloorLight2);}
		if (SensorValue(ElevatorEncoder)<LEDThresholdFloor3){turnLEDOff(FloorLight3);}



		if (SensorValue(ElevatorEncoder)>LEDThresholdFloor1){
			turnLEDOn(FloorLight1);
		}

		if (SensorValue(ElevatorEncoder)
			<LEDThresholdFloor2 && SensorValue(ElevatorEncoder)>LEDThresholdFloor3){
			turnLEDOn(FloorLight2);
		}



		if (SensorValue(ElevatorEncoder)<LEDThresholdFloor3){
			turnLEDOn(FloorLight3);
		}

	}


	//	if (SensorValue[ElevatorEncoder] < TargetPose - SlowError) {
		//startMotor(ElevateMotor, PIDSpeedUp);
	//	}
	//	if (SensorValue[ElevatorEncoder] > TargetPose + SlowError) {
	//	startMotor(ElevateMotor, PIDSpeedDown);
	//	}

	//	if((SensorValue[ElevatorEncoder] - TargetPose)<5){
	//		}




}
