#pragma config(Sensor, dgtl1,  FloorLight1,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  FloorLight2,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  FloorLight3,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  CallFloor1,     sensorTouch)
#pragma config(Sensor, dgtl5,  CallFloor2,     sensorTouch)
#pragma config(Sensor, dgtl6,  CallFloor3,     sensorTouch)
#pragma config(Sensor, dgtl7,  SendFloor1,     sensorTouch)
#pragma config(Sensor, dgtl8,  SendFloor2,     sensorTouch)
#pragma config(Sensor, dgtl9,  SendFloor3,     sensorTouch)
#pragma config(Sensor, dgtl10, ElevatorEncoder, sensorQuadEncoder)
#pragma config(Motor,  port2,  ElevateMotor,  tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


const int FastMove = 45;
const int FastMoveDown = 35;
const int MoveSpeed = 30;
const int MoveSpeedDown= 22;
const int PIDSpeedUp = 25;
const int PIDSpeedDown = 11;
const int Level1Setpoint = -10;
const int Level2Setpoint = -165;
const int Level3Setpoint = -347;
const int LEDThresholdFloor1 = -131;
const int LEDThresholdFloor2 = -131;
const int LEDThresholdFloor3 = -279.5;

int TargetPose=0;
int Startcount =0;
task main() {
 startMotor(ElevateMotor,15);

 while(Startcount<10){
 turnLEDOn(FloorLight1);turnLEDOn(FloorLight2);turnLEDOn(FloorLight3);
 wait(.25);
 turnLEDOff(FloorLight1);turnLEDOff(FloorLight2);turnLEDOff(FloorLight3);
 wait(.25);
 Startcount=Startcount+1;
}
 stopMotor(ElevateMotor);
 SensorValue(ElevatorEncoder) = 0;
 TargetPose=Level1Setpoint;
	while (true) {

if (SensorValue[ElevatorEncoder] > (TargetPose-3) && (SensorValue[ElevatorEncoder] < (TargetPose+3)))
				{
		stopMotor(ElevateMotor);

		}

		if (SensorValue[ElevatorEncoder] < (TargetPose-40)) {
		startMotor(ElevateMotor, FastMoveDown);
		}
		if (SensorValue[ElevatorEncoder] > (TargetPose+40)) {
		startMotor(ElevateMotor, -FastMove);
		}



		if (SensorValue[ElevatorEncoder] < (TargetPose-20)) {
		startMotor(ElevateMotor, MoveSpeedDown);
		}
		if (SensorValue[ElevatorEncoder] > (TargetPose+20)) {
		startMotor(ElevateMotor, -MoveSpeed);
		}

		if (SensorValue[ElevatorEncoder] < (TargetPose-10)) {
		startMotor(ElevateMotor, PIDSpeedDown);
		}
		if (SensorValue[ElevatorEncoder] > (TargetPose+10)) {
		startMotor(ElevateMotor, -PIDSpeedUp);

}


		if (SensorValue[CallFloor1]==1) {
		TargetPose = Level1Setpoint;
		}
		if (SensorValue[CallFloor2]==1) {
		TargetPose = Level2Setpoint;
		}
		if (SensorValue[CallFloor3]==1) {
		TargetPose = Level3Setpoint;
	}


			if (SensorValue[SendFloor1]==1) {
		TargetPose = Level1Setpoint;
		}
		if (SensorValue[SendFloor2]==1) {
		TargetPose = Level2Setpoint;
		}
		if (SensorValue[SendFloor3]==1) {
		TargetPose = Level3Setpoint;
	}
		if (SensorValue(ElevatorEncoder)<LEDThresholdFloor1){turnLEDOff(FloorLight1);}
		if (SensorValue(ElevatorEncoder)>LEDThresholdFloor1){turnLEDOff(FloorLight2);}
		if (SensorValue(ElevatorEncoder)<LEDThresholdFloor3){turnLEDOff(FloorLight2);}
		if (SensorValue(ElevatorEncoder)>LEDThresholdFloor3){turnLEDOff(FloorLight3);}



		if (SensorValue(ElevatorEncoder)>LEDThresholdFloor1){
			turnLEDOn(FloorLight1);
		}

		if (SensorValue(ElevatorEncoder)
			<LEDThresholdFloor2 && SensorValue(ElevatorEncoder)>LEDThresholdFloor3){
			turnLEDOn(FloorLight2);
		}



		if (SensorValue(ElevatorEncoder)<LEDThresholdFloor3){
			turnLEDOn(FloorLight3);
		}

}




}
